server:
  port: 80
spring:
  application:
    name: waimai
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/waimai?serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    hiddenmethod:
      filter:
        enabled: true
mybatis-plus:
  configuration:
#    在映射实体或属性时,将数据库表中的下划线-->驼峰
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
#reggie:
#  path: E:\\reggie\\img\\
# 分页配置参数
pagehelper:
  page-size-zero: true
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
waimai:
  path: D:\img\
#  指定mybatis日志级别
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
